version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:3.8.14
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  publisher:
    image: rabbitmq_test/publisher:1.0.0
    build:
      context: ./publisher
    stdin_open: true
    tty: true
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
    volumes:
      - ./publisher:/app:cached
      - ruby_bundle:/usr/local/
    depends_on:
      - rabbitmq

  consumer:
    image: rabbitmq_test/consumer:1.0.0
    build:
      context: ./consumer
    stdin_open: true
    tty: true
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
    volumes:
      - ./consumer:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - rabbitmq

volumes:
  ruby_bundle:
  node_modules:
